version: "3"

services:
  api:
    build: ./api
    environment:
      - DB_HOST=calendar-db
      - DB_PORT=27017
    ports:
      - "3000:3000"
    depends_on:
      - db
    container_name: calendar-api

  client:
    build: ./client
    ports:
      - "8080:80"
    container_name: calendar-client

  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: calendar-db